In [1]:
import pandas as pd
import numpy as np
from sklearn import preprocessing

C:\Users\ayesha.amjad\AppData\Roaming\Python\Python37\site-packages\pandas\compat\_optional.py:138: UserWarning: Pandas requires version '2.7.0' or newer of 'numexpr' (version '2.6.9' currently installed).
  warnings.warn(msg, UserWarning)

In [2]:
import pandas as pd
import sklearn
from sklearn.metrics import confusion_matrix
import evalml
from sklearn.metrics import cohen_kappa_score
import argparse
from scipy import stats
import numpy as np;
from sklearn.metrics import roc_curve, roc_auc_score
import matplotlib.pyplot as plt
from sklearn.preprocessing import MinMaxScaler

C:\Users\ayesha.amjad\AppData\Roaming\Python\Python37\site-packages\woodwork\__init__.py:23: FutureWarning: Woodwork may not support Python 3.7 in next non-bugfix release.
  "Woodwork may not support Python 3.7 in next non-bugfix release.", FutureWarning
Featuretools may not support Python 3.7 in next non-bugfix release.

In [3]:
from sklearn.model_selection import train_test_split
import seaborn as sns

In [4]:
import xgboost as xgb
import pandas as pd
from sklearn.metrics import mean_squared_error
from sklearn.model_selection import train_test_split

In [5]:
from sklearn import preprocessing
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import LabelEncoder

In [6]:
from sklearn.model_selection import train_test_split, RepeatedKFold, GridSearchCV, cross_val_score
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.preprocessing import MinMaxScaler

In [7]:
from sklearn.ensemble import RandomForestRegressor

Import Data

In [8]:
data=pd.read_csv(r'C:\Users\ayesha.amjad\Desktop\Self Learning\MS_DataScience\ML-1\machine-learning-spring23-challenge-1\training.csv')
print(data.shape)

(150000, 132)

In [9]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150000 entries, 0 to 149999
Columns: 132 entries, row ID to loss
dtypes: float64(15), int64(1), object(116)
memory usage: 151.1+ MB

In [10]:
cat_features = list(data.select_dtypes(include=['object']).columns)
print ("Categorical features:",len(cat_features))
print(cat_features)

Categorical features: 116
['s1', 's2', 's3', 's4', 's5', 's6', 's7', 's8', 's9', 's10', 's11', 's12', 's13', 's14', 's15', 's16', 'cat1', 'cat2', 'cat3', 'cat4', 'cat5', 'cat6', 'cat7', 'cat8', 'cat9', 'cat10', 'cat11', 'cat12', 'cat13', 'cat14', 'cat15', 'cat16', 'cat17', 'cat18', 'cat19', 'cat20', 'cat21', 'cat22', 'cat23', 'cat24', 'cat25', 'cat26', 'cat27', 'cat28', 'cat29', 'cat30', 'cat31', 'cat32', 'cat33', 'cat34', 'cat35', 'cat36', 'cat37', 'cat38', 'cat39', 'cat40', 'cat41', 'cat42', 'cat43', 'cat44', 'cat45', 'cat46', 'cat47', 'cat48', 'cat49', 'cat50', 'cat51', 'cat52', 'cat53', 'cat54', 'cat55', 'cat56', 'cat57', 'cat58', 'cat59', 'cat60', 'cat61', 'cat62', 'cat63', 'cat64', 'cat65', 'cat66', 'cat67', 'cat68', 'cat69', 'cat70', 'cat71', 'cat72', 'cat73', 'cat74', 'cat75', 'cat76', 'cat77', 'cat78', 'cat79', 'cat80', 'cat81', 'cat82', 'cat83', 'cat84', 'cat85', 'cat86', 'cat87', 'cat88', 'cat89', 'cat90', 'cat91', 'cat92', 'cat93', 'cat94', 'cat95', 'cat96', 'cat97', 'cat98', 'cat99', 'cat100']

Test/Train Split

In [11]:
#target = "loss"
#train_data, test_data = train_test_split(data, test_size=0.2, random_state=42)
#X_test=test_data.drop(columns=[target])
#Xtest_onehot = pd.get_dummies(X)
#Xtest_onehot

Define X/Y and Perform Encodings

In [12]:
target = "loss"

In [13]:
#data['loss'].describe()

In [15]:
X=data.drop(columns=[target])
y=data[target]
y

0         3325.946771
1         2212.393559
2         3903.026647
3         2045.297525
4         3479.835087
             ...
149995    5952.166732
149996    2088.160981
149997    2492.788255
149998    1910.452616
149999    6618.873731
Name: loss, Length: 150000, dtype: float64

In [16]:
X =X.drop(columns=['row ID'])

In [17]:
#y=np.log(y)

In [18]:
categorical_columns = [col for col in X.columns if X[col].dtype == 'object']

In [19]:
for col in categorical_columns:
    le = LabelEncoder()
    X[col] = le.fit_transform(X[col])

In [21]:
X.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150000 entries, 0 to 149999
Columns: 130 entries, s1 to cat100
dtypes: float64(14), int32(116)
memory usage: 82.4 MB

In [22]:
#X_onehot = pd.get_dummies(X)
#X_onehot

Feature Scaling

In [23]:
#scaler = MinMaxScaler(feature_range=(0, 1))
#X_Scaled = scaler.fit_transform(X)
#XS = pd.DataFrame(X_Scaled)
#XS.columns = X.columns
#XS

In [24]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size = 0.2)

In [25]:

# Define the XGBoost model
xg_reg = xgb.XGBRegressor(objective ='reg:squarederror', colsample_bytree = 0.5, learning_rate = 0.1,
                max_depth = 5, alpha = 10, n_estimators = 300)

In [130]:
# Train the model
xg_reg.fit(X,y)

# Make predictions on the test set
y_pred = xg_reg.predict(X)

# Calculate the root mean squared error (RMSE) of the predictions
rmse = np.sqrt(mean_squared_error(y, y_pred))
print("XGBoost: %f" % (rmse))

XGBoost: 1198.272448

In [147]:
# Train the model
xg_reg.fit(X_train,y_train)

# Make predictions on the test set
y_pred = xg_reg.predict(X_test)

rmse = np.sqrt(mean_squared_error(y_test, y_pred))
print("XGBoost: %f" % (rmse))

XGBoost: 1247.419184

In [148]:
parameters = {'colsample_bytree' : [0.3,0.5],
               'learning_rate' : [0.1,0.2],
                'n_estimators' : [100,300],#,400],
                'max_depth'    : [3,5]
                }
gbr = xgb.XGBRegressor(objective ='reg:squarederror')
cv = RepeatedKFold(n_splits=10, n_repeats=1)#, random_state=1)
grid_search = GridSearchCV(gbr, parameters, cv=cv, n_jobs=-1,verbose=3)#, refit=False)
grid_search.fit(X, y)
print(grid_search.best_estimator_)
print(grid_search.best_score_)
print(grid_search.best_params_)

Fitting 10 folds for each of 16 candidates, totalling 160 fits
XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=0.5, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             gamma=None, gpu_id=None, grow_policy=None, importance_type=None,
             interaction_constraints=None, learning_rate=0.1, max_bin=None,
             max_cat_threshold=None, max_cat_to_onehot=None,
             max_delta_step=None, max_depth=5, max_leaves=None,
             min_child_weight=None, missing=nan, monotone_constraints=None,
             n_estimators=300, n_jobs=None, num_parallel_tree=None,
             predictor=None, random_state=None, ...)
0.4830751597236434
{'colsample_bytree': 0.5, 'learning_rate': 0.1, 'max_depth': 5, 'n_estimators': 300}

In [ ]:
# Don't Run this code - takes 10+ minutes
cv = RepeatedKFold(n_splits=10, n_repeats=3, random_state=1)
#regRF = RandomForestRegressor(max_depth=5, random_state=0)
regRF = RandomForestRegressor(random_state=0)
param_grid = {
    'bootstrap': [True],
    'max_depth': [5, 10, 15],
    'max_features': [2, 3, 4],    
    'min_samples_split': [8, 10, 12],
    'n_estimators': [100, 200, 300] 
}
grid_search = GridSearchCV(estimator = regRF, param_grid=param_grid, cv = cv, n_jobs = -1, verbose = 2)
grid_search.fit(X, y)
best_grid = grid_search.best_estimator_
print(best_grid)

Fitting 30 folds for each of 81 candidates, totalling 2430 fits

PREDICTION (Ignore)

In [68]:
test_data = pd.read_csv('testing.csv')

In [69]:
Xtest_onehot = pd.get_dummies(test_data)
Xtest_onehot

,row ID,f1,f2,f3,f4,f5,f6,f7,f8,f9,...,cat100_F,cat100_G,cat100_H,cat100_I,cat100_J,cat100_K,cat100_L,cat100_M,cat100_N,cat100_O
0,200001,0.366788,0.359249,0.345247,0.726792,0.302678,0.364464,0.401162,0.26847,0.46226,...,0,0,0,0,1,0,0,0,0,0
1,200002,0.385085,0.377003,0.516660,0.340325,0.281143,0.570733,0.547756,0.80438,0.44352,...,1,0,0,0,0,0,0,0,0,0
2,200003,0.457203,0.447145,0.301535,0.205651,0.525831,0.411902,0.593548,0.31796,0.38846,...,0,0,0,0,0,0,1,0,0,0
3,200004,0.678924,0.665644,0.684242,0.407411,0.551723,0.688705,0.437192,0.67263,0.83505,...,0,0,0,0,1,0,0,0,0,0
4,200005,0.338312,0.366307,0.339244,0.793518,0.783230,0.373500,0.381883,0.36083,0.44352,...,0,0,0,1,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29995,229996,0.757468,0.772574,0.812550,0.843080,0.281143,0.806951,0.555567,0.74629,0.93383,...,0,1,0,0,0,0,0,0,0,0
29996,229997,0.705501,0.692256,0.357400,0.283936,0.895958,0.437758,0.535749,0.54236,0.47900,...,1,0,0,0,0,0,0,0,0,0
29997,229998,0.415029,0.406090,0.354344,0.377315,0.281143,0.502705,0.473897,0.43518,0.66201,...,1,0,0,0,0,0,0,0,0,0
29998,229999,0.863052,0.852865,0.654753,0.721707,0.340543,0.704364,0.562866,0.34987,0.44767,...,0,0,0,0,0,0,1,0,0,0
29999,230000,0.932195,0.946432,0.810511,0.721460,0.281143,0.844563,0.533048,0.97123,0.93383,...,0,0,0,1,0,0,0,0,0,0

In [70]:
scaler = MinMaxScaler(feature_range=(0, 1))
Xtest_Scaled = scaler.fit_transform(Xtest_onehot)
XS_test = pd.DataFrame(Xtest_Scaled)
XS_test.columns = Xtest_onehot.columns
XS_test

,row ID,f1,f2,f3,f4,f5,f6,f7,f8,f9,...,cat100_F,cat100_G,cat100_H,cat100_I,cat100_J,cat100_K,cat100_L,cat100_M,cat100_N,cat100_O
0,0.000000,0.344066,0.335705,0.349116,0.822297,0.030704,0.357327,0.356432,0.042499,0.465106,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
1,0.000033,0.363059,0.354156,0.522564,0.240551,0.000000,0.566848,0.513976,0.763467,0.446247,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.000067,0.437918,0.427053,0.304885,0.037827,0.348868,0.405513,0.563188,0.109078,0.390838,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
3,0.000100,0.668067,0.654135,0.692136,0.341535,0.385784,0.686680,0.395153,0.586221,0.840255,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
4,0.000133,0.314508,0.343040,0.343041,0.922739,0.715859,0.366506,0.335713,0.166752,0.446247,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29995,0.999867,0.749596,0.765265,0.821967,0.997345,0.000000,0.806790,0.522370,0.685317,0.939660,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
29996,0.999900,0.695654,0.681792,0.361413,0.155668,0.876583,0.431777,0.501072,0.410967,0.481951,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
29997,0.999933,0.394141,0.384386,0.358321,0.296231,0.000000,0.497748,0.434600,0.266776,0.666120,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
29998,0.999967,0.859194,0.848710,0.662296,0.814643,0.084691,0.702586,0.530214,0.152007,0.450423,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
29999,1.000000,0.930965,0.945952,0.819904,0.814271,0.000000,0.844995,0.498169,0.987933,0.939660,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0

In [71]:
XS_columns=XS.columns
XSTest_columns=XS_test.columns

In [72]:
if XS_columns.equals(XSTest_columns):
    print("The data has the same columns")
else:
    print("The data has different columns:")
    print("Columns in training data:", XS_columns)
    print("Columns in test data:", XSTest_columns)

The data has different columns:
Columns in training data: Index(['row ID', 'f1', 'f2', 'f3', 'f4', 'f5', 'f6', 'f7', 'f8', 'f9',
       ...
       'cat100_F', 'cat100_G', 'cat100_H', 'cat100_I', 'cat100_J', 'cat100_K',
       'cat100_L', 'cat100_M', 'cat100_N', 'cat100_O'],
      dtype='object', length=1059)
Columns in test data: Index(['row ID', 'f1', 'f2', 'f3', 'f4', 'f5', 'f6', 'f7', 'f8', 'f9',
       ...
       'cat100_F', 'cat100_G', 'cat100_H', 'cat100_I', 'cat100_J', 'cat100_K',
       'cat100_L', 'cat100_M', 'cat100_N', 'cat100_O'],
      dtype='object', length=1020)

In [73]:
extra_columns_test = set(XSTest_columns) - set(XS_columns)
extra_columns_train = set(XS_columns) - set(XSTest_columns)

In [74]:
print(extra_columns_train)

{'s7_DB', 's8_AO', 's8_BM', 's1_AT', 's8_AK', 's3_G', 's1_JI', 's1_AE', 's1_KG', 's1_FI', 's7_CB', 's1_FN', 's16_E', 's7_BM', 's6_F', 's4_P', 's14_L', 's7_DD', 's1_AN', 's4_AC', 's8_BF', 's1_CJ', 's1_BI', 's1_L', 's4_B', 's1_DR', 's8_BP', 's7_BY', 's1_AD', 's1_JK', 's1_BT', 's7_AN', 's1_CC', 's8_ZZ', 's1_HE', 's7_Q', 's7_Y', 's8_CH', 's1_BW', 's1_AL', 's1_AK', 's8_AG', 's1_KF', 's7_S', 's1_AU', 's1_FS', 's1_JH', 's4_AP', 's8_B', 's1_AH', 's1_BG', 's1_IJ', 's8_AF', 's7_H', 's16_H', 'cat89_G', 's1_BM', 's15_F', 'cat99_O', 's1_KV', 's7_DV', 's1_JA', 's1_CL', 's1_AR', 's16_N', 's7_BV', 's1_GQ', 's7_DQ', 's7_DT', 's8_BV', 's1_BF', 's16_B', 's1_FQ', 's1_IV', 's1_IB', 's7_EI', 's1_EV', 's1_BL', 's7_BD', 's1_IK', 'cat89_E', 's8_BT', 's1_IO', 's1_EU', 'cat90_G', 's1_DQ', 's1_AM', 'cat89_I', 's1_DY', 's1_FJ', 's8_AV', 's8_CF', 's1_CY', 's4_V', 's1_AP', 's8_BK', 's1_AB', 's7_DN', 's1_FP', 's7_BK'}

In [76]:
XS = XS.drop(columns=extra_columns_train)
XS_test = XS_test.drop(columns = extra_columns_test)

In [77]:
XS_test

,row ID,f1,f2,f3,f4,f5,f6,f7,f8,f9,...,cat100_F,cat100_G,cat100_H,cat100_I,cat100_J,cat100_K,cat100_L,cat100_M,cat100_N,cat100_O
0,0.000000,0.344066,0.335705,0.349116,0.822297,0.030704,0.357327,0.356432,0.042499,0.465106,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
1,0.000033,0.363059,0.354156,0.522564,0.240551,0.000000,0.566848,0.513976,0.763467,0.446247,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.000067,0.437918,0.427053,0.304885,0.037827,0.348868,0.405513,0.563188,0.109078,0.390838,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
3,0.000100,0.668067,0.654135,0.692136,0.341535,0.385784,0.686680,0.395153,0.586221,0.840255,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
4,0.000133,0.314508,0.343040,0.343041,0.922739,0.715859,0.366506,0.335713,0.166752,0.446247,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29995,0.999867,0.749596,0.765265,0.821967,0.997345,0.000000,0.806790,0.522370,0.685317,0.939660,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
29996,0.999900,0.695654,0.681792,0.361413,0.155668,0.876583,0.431777,0.501072,0.410967,0.481951,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
29997,0.999933,0.394141,0.384386,0.358321,0.296231,0.000000,0.497748,0.434600,0.266776,0.666120,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
29998,0.999967,0.859194,0.848710,0.662296,0.814643,0.084691,0.702586,0.530214,0.152007,0.450423,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
29999,1.000000,0.930965,0.945952,0.819904,0.814271,0.000000,0.844995,0.498169,0.987933,0.939660,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0

In [78]:
# Define the XGBoost model
xg_reg = xgb.XGBRegressor(objective ='reg:squarederror', colsample_bytree = 0.3, learning_rate = 0.1,
                max_depth = 5, alpha = 10, n_estimators = 300)

# Train the model
xg_reg.fit(XS,y)

# Make predictions on the test set
y_pred = xg_reg.predict(XS)

# Calculate the root mean squared error (RMSE) of the predictions
rmse = np.sqrt(mean_squared_error(y, y_pred))
print("RMSE: %f" % (rmse))

RMSE: 1201.505295

In [81]:
import numpy as np

In [79]:
predictions = xg_reg.predict(XS_test)
print(predictions)

[4782.7983 2413.7722 7146.479  ... 3063.7715 4284.36   3844.5298]

In [84]:
predictions_df=pd.DataFrame(predictions, columns=['loss'])
predictions_df

              loss
0      4782.798340
1      2413.772217
2      7146.479004
3      2700.666748
4      3608.759521
...            ...
29995  3964.792236
29996  4910.355957
29997  3063.771484
29998  4284.359863
29999  3844.529785

[30000 rows x 1 columns]

In [85]:
predictions_df.insert(0, 'row ID', range(200001, 230001))

In [86]:
predictions_df

       row ID         loss
0      200001  4782.798340
1      200002  2413.772217
2      200003  7146.479004
3      200004  2700.666748
4      200005  3608.759521
...       ...          ...
29995  229996  3964.792236
29996  229997  4910.355957
29997  229998  3063.771484
29998  229999  4284.359863
29999  230000  3844.529785

[30000 rows x 2 columns]

In [87]:
predictions_df.to_csv('predictions23.csv', sep=',', index=False)